onebeyond/maintainers

- .gitignore
- Added common text editors
- Added Operative Systems
> chore: added basic git ignore rules

- meetings/2022-11-22.md
Here are the meeting notes:
- Please review: @onebeyond/maintainers and @cesarD @betisman @inigomarquinez @w3dani @jgleal @carpasse
- Close #7
> feat: added meeting notes 22-11-2022

- README.md
- how-to/manage-teams.md
- Added documentation about teams management
- Improved the `Readme.md` with some context and useful links.
Please @onebeyond/maintainers have a look ;)
> Improve documentation

- meetings/2023-01-10.md
Here are the meeting notes:
- Please review: @onebeyond/maintainers and @onebeyond/admins
- Close #18
> chore: added meeting notes for 2023-01-10

- docs/meetings/2023-02-09.md
Please have a look @onebeyond/maintainers. I made a copy/paste/merge with the notes from the doc and the notes from @inigomarquinez 
Close #44
> Added notes for 2023-02-09

- .github/workflows/security-scoring.yml
- docs/reporting/scorecard.md
- Bump to `UlisesGascon/openssf-scorecard-monitor@v2.0.0-beta2` (5014c58)
- Restored reporting template in order to include more context (0aebf57)
- 0aebf57 fix: restored reporting template by @UlisesGascon
- 5014c58 chore: bump pipeline dependency version by @UlisesGascon
> Feat: scorecard reporting improvements

- docs/meetings/2023-03-23.md
Add 2023-03-23 meeting minutes.
Please have a look @onebeyond/maintainers.
https://github.com/onebeyond/maintainers/issues/1
https://github.com/onebeyond/maintainers/issues/15
https://github.com/onebeyond/maintainers/issues/21
https://github.com/onebeyond/maintainers/issues/28
https://github.com/onebeyond/maintainers/issues/29
https://github.com/onebeyond/maintainers/issues/41
https://github.com/onebeyond/maintainers/issues/42
https://github.com/onebeyond/maintainers/issues/51
https://github.com/onebeyond/maintainers/issues/56
https://github.com/onebeyond/maintainers/issues/58
https://github.com/onebeyond/maintainers/issues/59
https://github.com/onebeyond/maintainers/issues/60
Close #57
> 2023-03-23 meeting minutes

- docs/meetings/2023-04-20.md
close https://github.com/onebeyond/maintainers/issues/69
> docs: meeting minutes for 2023-04-20

- .github/workflows/security-scoring.yml
Upgrade dependency
This version will improve the way we review the scores
> chore: upgrade scorecard-monitor version

- docs/meetings/2023-05-18.md
> docs: meeting minutes for 2023-05-18

- docs/governance/projects.mdx
As discussed in #75, I created a classification for all the projects in this organization. 
Please, feel free to propose changes in the Leader/team or tier if is not clear for you ;-)
- close #75 
- Related to classification definition from #80 
N/A
N/A
N/A
> Added projects classification by tiers

- docs/meetings/2023-06-01.md
> Added meeting notes 01-06-2023

- docs/governance/tiers.mdx
Extended tiers to document a bit the requirements to change between tiers
N/A
N/A 
N/A
> Extend tiers

- docs/open-source-manifesto.mdx
**Context**
- close #84 
- Preview in https://deploy-preview-90--onebeyond-maintainers.netlify.app/open-source-manifesto
**Internal Company discussions:**
- [Slack](https://one-beyond.slack.com/archives/CLWU3EG1F/p1685433635616979)
- [Doc Draft with comments](https://dcslsoftwareltd-my.sharepoint.com/personal/ulises_gascon_one-beyond_com/_layouts/15/doc.aspx?sourcedoc={622930f5-5e6a-4b0d-bead-f9c298707295}&action=edit)
> feat: added Open Source Manifesto

- docs/open-source-manifesto.mdx
> docs: Ulises gascon signed the Open Source Manifesto

- docs/open-source-manifesto.mdx
Íñigo MarquÍnez Prado  signs the Open Souce manifesto
> docs: Íñigo MarquÍnez Prado  signs the Open Souce manifesto

- .gitignore
- docs/open-source-manifesto.mdx
chore: gitignore allows vim editing on windows
> docs: signature by Nick

- docs/meetings/2023-06-15.md
Meeting minutes for 2023-06-15
> docs: meeting minutes for 2023-06-15

- .github/workflows/security-scoring.yml
> chore: bump openssf-scorecard-monitor to v2.0.0-beta6

- docs/02-open-source-manifesto.mdx
As agreed [in Slack](https://one-beyond.slack.com/archives/D05APPH5GCB/p1687774748100849) I made this PR for him.
> docs: JOD signs the document

- docs/03-meetings/2023-06-29.md
[Preview available](https://deploy-preview-106--onebeyond-maintainers.netlify.app/meetings/2023-06-29)
close #104
> Added meeting notes for 2023-06-29

- docs/07-newsletters/2023-06.mdx
- [Preview](https://deploy-preview-103--onebeyond-maintainers.netlify.app/newsletters/june-2023)
> June'23 newsletter

- docs/02-open-source-manifesto.mdx
[Carlos Jiménez](https://github.com/betisman) signs the Open Source manifesto
> docs: sign manifest (@betisman)

- docs/02-open-source-manifesto.mdx
[Matteo Di Paolantonio](https://github.com/matteodipaolo) signs the Open Source manifesto
> docs: sign manifest (@matteodipaolo)

- docs/05-governance/03-projects.mdx
> Added new tier 3 projects

- docs/03-meetings/2023-07-13.md
Added meeting notes
close #112
> Added meeting notes for 2023-07-13

- docs/07-newsletters/2023-07.mdx
- [Preview](https://deploy-preview-123--onebeyond-maintainers.netlify.app/newsletters/2023-07)
> July'23 newsletter

- docs/07-newsletters/2023-07.mdx
Added minor changes based on Slack discussion.
> Update July'23 newsletter

- docs/03-meetings/2023-09-07.md
[Preview available](https://deploy-preview-134--onebeyond-maintainers.netlify.app/meetings/2023-09-07)
close #130
> Added meeting notes for 2023-09-07

- docs/05-governance/02-tiers.mdx
Update checklist for a project to be moved to Tier 1
As we're standardizing several aspects of the repositories (badges, code climate, ...) we think it's useful to do it a requirement for at least tier 1 projects.
> docs: update tiers

- docs/03-meetings/2023-09-21.md
> Added last meeting notes

- docs/07-newsletters/2023-09.md
- docs/07-newsletters/2023-09.mdx
- [Preview](https://deploy-preview-138--onebeyond-maintainers.netlify.app/newsletters/september-2023)
> Sep'23 newsletter

- docs/07-newsletters/2023-09.mdx
- docs/07-newsletters/2023-10.mdx
- [Preview](https://deploy-preview-148--onebeyond-maintainers.netlify.app/newsletters/october-2023)
> Oct'23 newsletter 

- .github/workflows/security-scoring.yml
This change will make the scorecard monitor to generate PR in state of directly commit to `main` branch
> scorecard monitor will generate PRs

- docs/07-newsletters/2023-12.mdx
> newsletter dec 2023

- docs/07-newsletters/2024-01.mdx
> newsletter jan 2024

- docs/07-newsletters/2024-02.mdx
**[Preview](https://deploy-preview-169--onebeyond-maintainers.netlify.app/newsletters/February-2024)**
**Missing Content**
> Newsletter Feb 2024

- docs/07-newsletters/2024-03.mdx
**[Preview](https://deploy-preview-192--onebeyond-maintainers.netlify.app/newsletters/March-2024)**
**Missing Content**
> Newsletter March 2024

- docs/07-newsletters/2024-04.mdx
**[Preview](https://deploy-preview-205--onebeyond-maintainers.netlify.app/newsletters/April-2024)**
**Missing Content**
> Newsletter April 2024
